export const SIDEBAR_MENU_ROUTES = {
  dashboard: '/dashboard',
  visiMisiTujuan: '/visi-misi-tujuan',
  sasaranStrategis: '/sasaran-strategis',
  perjanjianKinerja: '/perjanjian-kinerja',
  sasaranProgram: '/sasaran-program',
  sasaranKegiatan: '/sasaran-kegiatan',
  cascading: '/cascading',
  masterUnitKerja: '/master-unit-kerja',
  masterUser: '/master-user',
  masterSasaranStrategis: '/sasaran-strategis',
  masterSasaranProgram: '/sasaran-program',
  masterSasaranKegiatan: '/sasaran-kegiatan',
  masterIndikatorKinerja: '/indikator-kinerja',
  rencanaAksi: '/rencana-aksi',
  pemantauanSasaranStrategis: '/pemantauan-kinerja/sasaran-strategis',
  pemantauanPerjanjianKinerja: '/pemantauan-kinerja/perjanjian-kinerja',
  pemantauanSasaranProgram: '/pemantauan-kinerja/sasaran-program',
  pemantauanSasaranKegiatan: '/pemantauan-kinerja/sasaran-kegiatan',
  pemantauanRencanaAksi: '/pemantauan-kinerja/rencana-aksi',
  laporanSasaranStrategis: '/laporan/sasaran-strategis',
  laporanPerjanjianKinerja: '/laporan/perjanjian-kinerja',
  laporanSasaranProgram: '/laporan/sasaran-program',
  laporanRencanaAksi: '/laporan/rencana-aksi',
} as const;
