export const SIDEBAR_MENU_ROUTES = {
  dashboard: '/dashboard',
  visiMisiTujuan: '/visi-misi-tujuan',
  sasaranStrategis: '/sasaran-strategis',
  perjanjianKinerja: '/perjanjian-kinerja',
  sasaranProgram: '/sasaran-program',
  sasaranKegiatan: '/sasaran-kegiatan',
  cascading: '/cascading',
  masterUnitKerja: '/master-unit-kerja',
  masterUser: '/master-user',
  rencanaAksi: '/rencana-aksi',
  pemantauanSasaranStrategis: '/pemantauan-kinerja/sasaran-strategis',
  laporanSasaranStrategis: '/laporan/sasaran-strategis',
  laporanPerjanjianKinerja: '/laporan/perjanjian-kinerja',
  laporanRencanaAksi: '/laporan/rencana-aksi',
} as const;
