import pg from 'pg';
import 'dotenv/config';

const pool = new pg.Pool({
  connectionString: process.env.DATABASE_URL,
});

async function run() {
  try {
    const queries = [
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS id_ss integer',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS id_is integer',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS id_sp integer',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS id_ip integer',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS unit_kerja varchar(500)',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS kode_iku varchar(500)',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS sasaran_kegiatan_text text',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS satuan varchar(255)',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS target_1 numeric',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS target_2 numeric',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS target_3 numeric',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS target_4 numeric',
      'ALTER TABLE sireva.sasaran_kegiatan ADD COLUMN IF NOT EXISTS target_5 numeric'
    ];

    for (const q of queries) {
      await pool.query(q);
    }
    
    // Identity fix
    try {
      await pool.query('ALTER TABLE sireva.sasaran_kegiatan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
    } catch (e: any) {
      console.log('Identity might already exist or needs different command:', e.message);
      // If it already exists, we might need to change it
      await pool.query('ALTER TABLE sireva.sasaran_kegiatan ALTER COLUMN id SET GENERATED BY DEFAULT');
    }

    console.log('Successfully standardized sasaran_kegiatan table');
    process.exit(0);
  } catch (e: any) {
    console.error('Migration failed:', e.message);
    process.exit(1);
  }
}

run();
